export type UniverseSector = { id: string; name: string; owner: string; neighbors: string[] }

export const UNIVERSE_SECTORS_XT: UniverseSector[] = [
  { id: 'aladna_hill', name: "Aladna Hill", owner: 'argon', neighbors: ["Hatikvah's Faith", "Light of Heart"] },
  { id: 'antigone_memorial', name: "Antigone Memorial", owner: 'argon', neighbors: ["Power Circle", "The Hole"] },
  { id: 'argon_prime', name: "Argon Prime", owner: 'argon', neighbors: ["Herron's Nebula", "Ringo Moon", "The Wall", "Home of Light"] },
  { id: 'atreus_clouds', name: "Atreus' Clouds", owner: 'boron', neighbors: ["Rolk's Fate", "The Hole", "Farnham's Legend"] },
  { id: 'bala_gi_s_joy', name: "Bala Gi's Joy", owner: 'pirat', neighbors: ["Farnham's Legend", "Olmancketslat's Treaty"] },
  { id: 'black_hole_sun', name: "Black Hole Sun", owner: 'argon', neighbors: ["Enemy sector", "Treasure Chest"] },
  { id: 'blue_profit', name: "Blue Profit", owner: 'teladi', neighbors: ["Greater Profit", "Ceo's Sprite"] },
  { id: 'bluish_snout', name: "Bluish Snout", owner: 'boron', neighbors: ["Menelaus' Paradise", "Ocean of Fantasy"] },
  { id: 'brennan_s_triumph', name: "Brennan's Triumph", owner: 'pirat', neighbors: ["Olmancketslat's Treaty", "Split Fire", "Danna's Chance"] },
  { id: 'ceo_s_buckzoid', name: "Ceo's Buckzoid", owner: 'teladi', neighbors: ["Menelaus' Frontier", "Teladi Gain", "Profit Share"] },
  { id: 'ceo_s_doubt', name: "Ceo's Doubt", owner: 'teladi', neighbors: ["New Income", "Great Trench"] },
  { id: 'ceo_s_sprite', name: "Ceo's Sprite", owner: 'teladi', neighbors: ["Blue Profit", "Company Pride"] },
  { id: 'chins_clouds', name: "Chin's Clouds", owner: 'split', neighbors: ["Family Pride", "Chin's Fire", "Tharka's Sun"] },
  { id: 'chins_fire', name: "Chin's Fire", owner: 'split', neighbors: ["Thuruk's Pride", "Chin's Clouds", "Family Chin"] },
  { id: 'cho_s_defeat', name: "Cho's Defeat", owner: 'split', neighbors: ["Tharka's Sun", "Patriarch's Keep"] },
  { id: 'cloudbase_north_west', name: "Cloudbase North West", owner: 'argon', neighbors: ["Three Worlds", "Herron's Nebula", "Ringo Moon"] },
  { id: 'cloudbase_south_east', name: "Cloudbase South East", owner: 'argon', neighbors: ["President's End", "Ore Belt"] },
  { id: 'cloudbase_south_west', name: "Cloudbase South West", owner: 'argon', neighbors: ["Red Light", "Ore Belt", "Emperor Mines"] },
  { id: 'company_pride', name: "Company Pride", owner: 'teladi', neighbors: ["Ceo's Sprite", "Thuruk's Beard"] },
  { id: 'danna_s_chance', name: "Danna's Chance", owner: 'pirat', neighbors: ["Brennan's Triumph", "Nopileo's Memorial"] },
  { id: 'dukes_domain', name: "Duke's Domain", owner: 'paranid', neighbors: ["Priest Rings", "Empire's Edge", "Emperor's Ridge"] },
  { id: 'eighteen_billion', name: "Eighteen Billion", owner: 'teladi', neighbors: ["Enemy sector", "Ianamus Zura"] },
  { id: 'elena_s_fortune', name: "Elena's Fortune", owner: 'pirat', neighbors: ["Farnham's Legend", "President's End", "Olmancketslat's Treaty", "Split Fire"] },
  { id: 'emperor_mines', name: "Emperor Mines", owner: 'paranid', neighbors: ["Cloudbase South West", "Paranid Prime"] },
  { id: 'emperors_ridge', name: "Emperor's Ridge", owner: 'paranid', neighbors: ["Priest's Pity", "Duke's Domain", "Pontifex' Realm"] },
  { id: 'empires_edge', name: "Empire's Edge", owner: 'paranid', neighbors: ["Paranid Prime", "Duke's Domain"] },
  { id: 'enemy_sector_11_07', name: "Enemy sector 11-07", owner: 'xenon', neighbors: ["Scale Plate Green", "Eighteen Billion"] },
  { id: 'enemy_sector_15_05', name: "Enemy sector 15-05", owner: 'xenon', neighbors: ["Thyn's Abyss", "Black Hole Sun"] },
  { id: 'enemy_sector_17_00', name: "Enemy sector 17-00", owner: 'xenon', neighbors: ["Getsu Fune"] },
  { id: 'enemy_sector_19_00', name: "Enemy sector 19-00", owner: 'xenon', neighbors: ["Enemy sector"] },
  { id: 'enemy_sector_19_01', name: "Enemy sector 19-01", owner: 'xenon', neighbors: ["Enemy sector", "Menelaus' Paradise"] },
  { id: 'family_chin', name: "Family Chin", owner: 'split', neighbors: ["Chin's Fire", "Thuruk's Beard"] },
  { id: 'family_njy', name: "Family Njy", owner: 'split', neighbors: ["Ghinn's Escape", "Thyn's Abyss"] },
  { id: 'family_pride', name: "Family Pride", owner: 'split', neighbors: ["Thuruk's Pride", "Chin's Clouds"] },
  { id: 'family_whi', name: "Family Whi", owner: 'split', neighbors: ["Teladi Gain", "Family Zein"] },
  { id: 'family_zein', name: "Family Zein", owner: 'split', neighbors: ["Family Whi", "Thuruk's Pride"] },
  { id: 'farnham_s_legend', name: "Farnham's Legend", owner: 'pirat', neighbors: ["Atreus' Clouds", "Bala Gi's Joy", "Elena's Fortune"] },
  { id: 'getsu_fune', name: "Getsu Fune", owner: 'boron', neighbors: ["Enemy sector", "Menelaus' Paradise"] },
  { id: 'ghinn_s_escape', name: "Ghinn's Escape", owner: 'split', neighbors: ["Hila's Joy", "Family Njy"] },
  { id: 'great_trench', name: "Great Trench", owner: 'boron', neighbors: ["Rolk's Legacy", "Ceo's Doubt"] },
  { id: 'greater_profit', name: "Greater Profit", owner: 'teladi', neighbors: ["Seizewell", "Spaceweed Drift", "Blue Profit"] },
  { id: 'hatikvah_s_faith', name: "Hatikvah's Faith", owner: 'pirat', neighbors: ["Thuruks Beard", "Nopileo's Memorial", "Aladna Hill"] },
  { id: 'herron_s_nebula', name: "Herron's Nebula", owner: 'argon', neighbors: ["Power Circle", "Cloudbase North West", "The Hole", "Argon Prime"] },
  { id: 'hila_s_joy', name: "Hila's Joy", owner: 'boron', neighbors: ["Ghinn's Escape", "Ocean of Fantasy"] },
  { id: 'ianamus_zura', name: "Ianamus Zura", owner: 'teladi', neighbors: ["Eighteen Billion", "New Income"] },
  { id: 'kingdom_end', name: "Kingdom End", owner: 'boron', neighbors: ["Rolk's Drift", "Three Worlds"] },
  { id: 'light_home', name: "Light Home", owner: 'argon', neighbors: ["Argon Prime", "Red Light", "President's End", "Ore Belt"] },
  { id: 'light_of_heart', name: "Light of Heart", owner: 'argon', neighbors: ["Aladna Hill", "Montalaar"] },
  { id: 'lucky_planets', name: "Lucky Planets", owner: 'boron', neighbors: ["Shore of Infinity", "Rolk's Legacy"] },
  { id: 'menelaus_frontier', name: "Menelaus' Frontier", owner: 'boron', neighbors: ["Queen's Space", "Ceo's Buckzoid", "Rolk's Fate"] },
  { id: 'menelaus_paradise', name: "Menelaus' Paradise", owner: 'boron', neighbors: ["Getsu Fune", "Enemy sector", "Bluish Snout"] },
  { id: 'montalaar', name: "Montalaar", owner: 'argon', neighbors: ["Light of Heart", "Rolk's Legacy"] },
  { id: 'new_income', name: "New Income", owner: 'teladi', neighbors: ["Ianamus Zura", "Ceo's Doubt"] },
  { id: 'nopileo_s_memorial', name: "Nopileo's Memorial", owner: 'pirat', neighbors: ["Danna's Chance", "Hatikvah's Faith"] },
  { id: 'nyana_s_hideout', name: "Nyana's Hideout", owner: 'argon', neighbors: ["Scale Plate Green", "Omicron Lyrae"] },
  { id: 'ocean_of_fantasy', name: "Ocean of Fantasy", owner: 'boron', neighbors: ["Bluish Snout", "Hila's Joy"] },
  { id: 'olmancketslat_s_treaty', name: "Olmancketslat's Treaty", owner: 'pirat', neighbors: ["Bala Gi's Joy", "Elena's Fortune", "Brennan's Triumph"] },
  { id: 'omicron_lyrae', name: "Omicron Lyrae", owner: 'argon', neighbors: ["Nyana's Hideout", "Treasure Chest"] },
  { id: 'ore_belt', name: "Ore Belt", owner: 'argon', neighbors: ["Home of Light", "Cloudbase South West", "Cloudbase South East"] },
  { id: 'paranid_prime', name: "Paranid Prime", owner: 'paranid', neighbors: ["Emperor Mines", "Priest Rings", "Empire's Edge"] },
  { id: 'patriarch_s_keep', name: "Patriarch's Keep", owner: 'split', neighbors: ["Cho's Defeat", "Two Grand"] },
  { id: 'pontifex_realm', name: "Pontifex' Realm", owner: 'paranid', neighbors: ["Emperor's Ridge", "Trinity Sanctum"] },
  { id: 'power_circle', name: "Power Circle", owner: 'argon', neighbors: ["Three Worlds", "Antigone Memorial", "Herron's Nebula"] },
  { id: 'preacher_s_refuge', name: "Preacher's Refuge", owner: 'paranid', neighbors: ["Trinity Sanctum", "Shore of Infinity"] },
  { id: 'president_s_end', name: "President's End", owner: 'argon', neighbors: ["The Wall", "Home of Light", "Elena's Fortune", "Cloudbase South East"] },
  { id: 'priest_pity', name: "Priest's Pity", owner: 'paranid', neighbors: ["Split Fire", "Priest Rings", "Emperor's Ridge"] },
  { id: 'priest_rings', name: "Priest Rings", owner: 'paranid', neighbors: ["Paranid Prime", "Priest's Pity", "Duke's Domain"] },
  { id: 'profit_center_alpha', name: "Profit Center Alpha", owner: 'teladi', neighbors: ["Two Grand", "PTNI Headquarters"] },
  { id: 'profit_share', name: "Profit Share", owner: 'teladi', neighbors: ["Ceo's Buckzoid", "Seizewell", "Spaceweed Drift"] },
  { id: 'ptni_headquarters', name: "PTNI Headquarters", owner: 'teladi', neighbors: ["Profit Center Alpha", "Scale Plate Green"] },
  { id: 'queens_space', name: "Queen's Space", owner: 'boron', neighbors: ["Rolk's Drift", "Menelaus' Frontier"] },
  { id: 'red_light', name: "Red Light", owner: 'argon', neighbors: ["Ringo Moon", "Home of Light", "Cloudbase South West"] },
  { id: 'ringo_moon', name: "Ringo Moon", owner: 'argon', neighbors: ["Cloudbase North West", "Argon Prime", "Red Light"] },
  { id: 'rolk_s_drift', name: "Rolk's Drift", owner: 'boron', neighbors: ["Kingdom End", "Queen's Space"] },
  { id: 'rolk_s_fate', name: "Rolk's Fate", owner: 'boron', neighbors: ["Menelaus' Frontier", "Atreus' Clouds"] },
  { id: 'rolk_s_legacy', name: "Rolk's Legacy", owner: 'boron', neighbors: ["Montalaar", "Lucky Planets", "Great Trench"] },
  { id: 'scale_plate_green', name: "Scale Plate Green", owner: 'teladi', neighbors: ["PTNI Headquarters", "Nyana's Hideout", "Enemy sector"] },
  { id: 'seizewell', name: "Seizewell", owner: 'teladi', neighbors: ["Teladi Gain", "Profit Share", "Greater Profit"] },
  { id: 'shore_of_infinity', name: "Shore of Infinity", owner: 'boron', neighbors: ["Preacher's Refuge", "Lucky Planets"] },
  { id: 'spaceweed_drift', name: "Spaceweed Drift", owner: 'teladi', neighbors: ["Profit Share", "Greater Profit"] },
  { id: 'split_fire', name: "Split Fire", owner: 'pirat', neighbors: ["Elena's Fortune", "Brennan's Triumph", "Priest's Pity"] },
  { id: 'teladi_gain', name: "Teladi Gain", owner: 'teladi', neighbors: ["Ceo's Buckzoid", "Family Whi", "Seizewell"] },
  { id: 'tharka_s_sun', name: "Tharka's Sun", owner: 'split', neighbors: ["Chin's Clouds", "Cho's Defeat"] },
  { id: 'the_hole', name: "The Hole", owner: 'argon', neighbors: ["Antigone Memorial", "Herron's Nebula", "Atreus' Clouds", "The Wall"] },
  { id: 'the_wall', name: "The Wall", owner: 'argon', neighbors: ["The Hole", "Argon Prime", "President's End"] },
  { id: 'three_worlds', name: "Three Worlds", owner: 'argon', neighbors: ["Kingdom End", "Power Circle", "Cloudbase North West"] },
  { id: 'thuruks_beard', name: "Thuruk's Beard", owner: 'split', neighbors: ["Family Chin", "Company Pride", "Hatikvah's Faith"] },
  { id: 'thuruks_pride', name: "Thuruk's Pride", owner: 'split', neighbors: ["Family Zein", "Family Pride", "Chin's Fire"] },
  { id: 'thyn_s_abyss', name: "Thyn's Abyss", owner: 'split', neighbors: ["Family Njy", "Enemy sector"] },
  { id: 'treasure_chest', name: "Treasure Chest", owner: 'argon', neighbors: ["Omicron Lyrae", "Black Hole Sun"] },
  { id: 'trinity_sanctum', name: "Trinity Sanctum", owner: 'paranid', neighbors: ["Pontifex' Realm", "Preacher's Refuge"] },
  { id: 'two_grand', name: "Two Grand", owner: 'teladi', neighbors: ["Patriarch's Keep", "Profit Center Alpha"] }
]

